name: Github actions demo
on: [push]

jobs:
 job1 :
   
    runs-on: ubuntu-latest
   
    steps:
    - name: Print hello world
      run : echo " I can print"
    
 job2 :
   runs-on: ubuntu-latest

   steps:
   - name: Print i can do git hub printing sentences
     run : echo "I can print  two sentences in github"

     
   
